<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" lang="fr">
<link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="../css/bootstrap-theme.min.css" />
<link rel="stylesheet" type="text/css" href="../css/monStyle.css" />
<link rel="icon" type="image/png" href="../img/question-icon.png">
<link rel="stylesheet" type="text/css" href="../css/bootstrap-select.min.css" />

<script src='../js/jquery-2.1.0.js'></script>
<script src='../js/bootstrap.min.js'></script>
<script src="../js/bootstrap-filestyle.js" type="text/javascript"></script>
<script src="../js/bootstrap-select.min.js" type="text/javascript"></script>